default_install_hook_types: [ pre-commit, pre-push, commit-msg ]
repos:
    -   repo: https://github.com/psf/black
        rev: 24.8.0  # Use the latest version of pylint available
        hooks:
            -   id: black
                entry: poetry run black .
                always_run: true
                stages: [ commit, push ]

    -   repo: https://github.com/pre-commit/mirrors-pylint
        rev: v3.0.0a5  # Use the latest version of pylint available
        hooks:
            -   id: pylint
                entry: poetry run pylint
                args: [ "--rcfile=.pylintrc" ]
                stages: [ commit ]
            -   id: pylint
                entry: poetry run pylint
                args: [ "--rcfile=.pylintrc", "src" ]
                always_run: true
                stages: [ push ]
